version: 2
jobs:
  build:
    docker:
      - image:  circleci/golang:1.13

    steps:
      - checkout
      - run: ls -la

      - run: mkdir /tmp/tests
      - run: mkdir /tmp/benchmark-results

      - run:
          name: Run tests
          command: gotestsum --junitfile /tmp/tests/unit-tests.xml

      - run:
          name: Run benchmarks
          command: |
            go test -benchmem -run=^$ -bench . | tee /tmp/benchmark-results/bechmark.txt

      - store_artifacts:
          path: /tmp/tests/
          destination: tests

      - store_artifacts:
          path: /tmp/benchmark-results
          destination: benchmarks