version: 2
jobs:
  build:
    docker:
      - image:  circleci/golang:1.13

    steps:
      - checkout
      - run: ls -la

      - run:
          name: Run tests
          command: gotestsum --junitfile /tmp/unit-tests.xml